ServerEvents.recipes(event => {
    event.recipes.create.pressing('chemlib:calcium_plate', 'chemlib:calcium_ingot'),
    event.recipes.create.pressing('chemlib:potassium_plate','chemlib:potassium_ingot'),
    event.recipes.create.pressing('chemlib:titanium_plate','chemlib:titanium_ingot'),
    event.recipes.create.pressing('chemlib:scandium_plate','chemlib:scandium_ingot'),
    event.recipes.create.pressing('chemlib:vanadium_plate','chemlib:vanadium_ingot'),
    event.recipes.create.pressing('chemlib:chromium_plate','chemlib:chromium_ingot'),
    event.recipes.create.pressing('chemlib:manganese_plate','chemlib:manganese_ingot'),
    event.recipes.create.pressing('chemlib:nickel_plate','chemlib:nickel_ingot'),
    event.recipes.create.pressing('chemlib:cobalt_plate','chemlib:cobalt_ingot'),
    event.recipes.create.pressing('chemlib:gallium_plate','chemlib:gallium_ingot'),
    event.remove({ output: 'chemlib:zinc_metal_block' }),
    event.remove({ input: 'chemlib:zinc_metal_block' }),
    event.remove({ output: 'chemlib:zinc_nugget' }),
    event.remove({ input: 'chemlib:zinc_nugget' }),
    event.remove({ output: 'chemlib:zinc_plate' }),
    event.remove({ input: 'chemlib:zinc_plate' }),
    event.remove({ output: 'chemlib:zinc_ingot' }),
    event.remove({ input: 'chemlib:zinc_ingot' }),
    event.remove({ input: 'chemlib:zinc_dust' }),
    event.smelting('create:zinc_ingot', 'chemlib:zinc_dust'),
    event.blasting('create:zinc_ingot', 'chemlib:zinc_dust'),
    event.remove({ output: 'chemlib:copper_plate' }),
    event.remove({ input: 'chemlib:copper_plate' }),
    event.remove({ output: 'mekanism:dust_copper' }),
    event.remove({ input: 'mekanism:dust_copper' }),
    event.recipes.create.crushing(['2x chemlib:potassium_dust'], 'sulfurpotassiummod:raw_potassium').processingTime(300),
    event.remove({ output: 'chemlib:potassium_ingot'}),
    event.smelting('sulfurpotassiummod:potassium', 'chemlib:potassium_dust'),
    event.recipes.create.compacting('chemlib:potassium_ingot', '4x sulfurpotassiummod:potassium'),
    event.remove({ output: 'chemlib:iron_plate' }),
    event.remove({ input: 'chemlib:iron_plate' }),
    event.remove({input: 'chemlib:iron_dust'}),
    event.remove({output: 'chemlib:iron_dust'})
})